version: '3.1'
services:
  db:
    container_name: postgres_db
    image: postgres:13.3
    restart: always
    hostname: localpg
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa55word
      POSTGRES_DB: simple-chat

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - /var/lib/pgadmin
    restart: always
    ports:
      - 8081:8081
    environment:
      PGADMIN_DEFAULT_EMAIL: localuser@example.org
      PGADMIN_DEFAULT_PASSWORD: Pa55word
      PGADMIN_LISTEN_PORT: 8081